version: '3.1'

services:
  wordpress:
   image: wordpress
   ports:
     - "8080:80"
   environment:
     WORDPRESS_DB_HOST: mydb
     WORDPRESS_DB_USER: exampleuser
     WORDPRESS_DB_PASSWORD: examplepass
     WORDPRESS_DB_NAME: exampledb
   volumes:
     - wordpress:/var/www/html

  mydb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mydb:/var/lib/mysql

volumes:
  wordpress:
  mydb:

