version: '3.1'

services:
   postgres:
      image: postgres
      secrets:
        - db_user
        - db_pass
      environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
        POSTGRES_USER_FILE: /run/secrets/db_user

secrets:
  db_user:
    file: ./db_user.txt
  db_pass:
    file: ./db_pass.txt
